# we only need to point to python for the tests to run
language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# command to install dependencies
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose
  - pip install -r requirements
  - pip install flake8

# command to run before the tests
before_script:
  - "flake8 tonicidentifier unittests --ignore=E501"

# command to run tests
script:
  - nosetests unittests
#  - nosetests --with-coverage
